import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent


def _load_config():
    config_path = HERE / "interface_config.json"
    if not config_path.exists():
        return {}
    try:
        return json.loads(config_path.read_text())
    except Exception:
        return {}


_config = _load_config()
REPO_NAME = _config.get("product_repo", "dev-in-portfolio/the-agent-command-center")
SOURCE_LINEAGE = _config.get("source_lineage", "dev-in-portfolio/agent-command-center-3")
RUNTIME_VERSION = _config.get("runtime_version_expected", "25.0.0")

ACTION_REGISTRY = {
    "show_status": {
        "action_id": "show_status",
        "label": "Show system status",
        "category": "safe",
        "risk_level": "none",
        "requires_approval": False,
        "writes_files": False,
        "runs_commands": False,
        "allowed_paths": [],
        "forbidden_capabilities": [],
        "menu_option": "1",
        "cli_flags": ["--status"],
        "description": "Display product repo, source lineage, runtime version, and locked/unlocked capabilities.",
        "recommended_next_action": "list_artifacts or run_validator_wall",
    },
    "run_validator_wall": {
        "action_id": "run_validator_wall",
        "label": "Run validator wall",
        "category": "controlled",
        "risk_level": "low",
        "requires_approval": False,
        "writes_files": False,
        "runs_commands": True,
        "allowed_paths": ["scripts/validate_*.py"],
        "forbidden_capabilities": ["mutate_validators"],
        "menu_option": "2",
        "cli_flags": ["--validator-wall"],
        "description": "Run all three validators (auto-self-improve-2, v25, v24) and display PASS/FAIL results.",
        "recommended_next_action": "generate_session_report or prepare_command_packet",
    },
    "list_artifacts": {
        "action_id": "list_artifacts",
        "label": "List artifact packages",
        "category": "safe",
        "risk_level": "none",
        "requires_approval": False,
        "writes_files": False,
        "runs_commands": False,
        "allowed_paths": ["09_exports/**"],
        "forbidden_capabilities": [],
        "menu_option": "3",
        "cli_flags": ["--list-artifacts"],
        "description": "List all artifact packages with file counts, key reports, and health status.",
        "recommended_next_action": "show_summaries or inspect_artifact_package",
    },
    "show_summaries": {
        "action_id": "show_summaries",
        "label": "Show latest trial / gauntlet summaries",
        "category": "safe",
        "risk_level": "none",
        "requires_approval": False,
        "writes_files": False,
        "runs_commands": False,
        "allowed_paths": ["09_exports/**/final_*.md"],
        "forbidden_capabilities": [],
        "menu_option": "4",
        "cli_flags": ["--show-summaries"],
        "description": "Display brief summaries from latest trial, gauntlet, and migration reports.",
        "recommended_next_action": "generate_session_report",
    },
    "generate_session_report": {
        "action_id": "generate_session_report",
        "label": "Generate operator session report",
        "category": "controlled",
        "risk_level": "low",
        "requires_approval": False,
        "writes_files": True,
        "runs_commands": False,
        "allowed_paths": ["09_exports/interface_phase_1/sessions/"],
        "forbidden_capabilities": [],
        "menu_option": "5",
        "cli_flags": ["--generate-session-report"],
        "description": "Write session report, result JSON, and optional validator/packet artifacts to session folder.",
        "recommended_next_action": "review session report",
    },
    "show_locked_actions": {
        "action_id": "show_locked_actions",
        "label": "Show locked actions",
        "category": "safe",
        "risk_level": "none",
        "requires_approval": False,
        "writes_files": False,
        "runs_commands": False,
        "allowed_paths": [],
        "forbidden_capabilities": [],
        "menu_option": "6",
        "cli_flags": ["--show-locked"],
        "description": "List all permanently locked actions that the interface refuses to perform.",
        "recommended_next_action": "show_status",
    },
    "prepare_command_packet": {
        "action_id": "prepare_command_packet",
        "label": "Prepare command packet",
        "category": "controlled",
        "risk_level": "low",
        "requires_approval": False,
        "writes_files": True,
        "runs_commands": False,
        "allowed_paths": ["09_exports/interface_phase_1/command_packets/"],
        "forbidden_capabilities": [],
        "menu_option": "7",
        "cli_flags": ["--prepare-packet"],
        "description": "Create a hardened command packet with packet_id, risk_level, preflight checks, and approval phrase.",
        "recommended_next_action": "review_packet_approval or show_approval_ledger",
    },
    "show_session_state": {
        "action_id": "show_session_state",
        "label": "Show current session state",
        "category": "safe",
        "risk_level": "none",
        "requires_approval": False,
        "writes_files": False,
        "runs_commands": False,
        "allowed_paths": [],
        "forbidden_capabilities": [],
        "menu_option": "8",
        "cli_flags": ["--session-state"],
        "description": "Display current session ID, branch, commit, action counts, and last action result.",
        "recommended_next_action": "generate_session_report or continue with safe/controlled actions",
    },
    "inspect_artifact_package": {
        "action_id": "inspect_artifact_package",
        "label": "Inspect artifact packages",
        "category": "safe",
        "risk_level": "none",
        "requires_approval": False,
        "writes_files": False,
        "runs_commands": False,
        "allowed_paths": ["09_exports/**"],
        "forbidden_capabilities": [],
        "menu_option": "9",
        "cli_flags": ["--inspect-artifacts", "--inspect-artifact"],
        "description": "Deep-inspect artifact packages: expected files, missing files, zero-byte files, final verdicts.",
        "recommended_next_action": "generate_session_report or show_summaries",
    },
    "prepare_branch_review": {
        "action_id": "prepare_branch_review",
        "label": "Prepare branch review packet",
        "category": "controlled",
        "risk_level": "low",
        "requires_approval": False,
        "writes_files": True,
        "runs_commands": True,
        "allowed_paths": ["09_exports/interface_phase_1/branch_reviews/"],
        "forbidden_capabilities": ["merge", "push", "delete_branch", "open_pr"],
        "menu_option": None,
        "cli_flags": ["--prepare-branch-review"],
        "description": "Inspect git diff and generate a branch review packet without merging, pushing, or deleting.",
        "recommended_next_action": "review_packet_approval",
    },
    "review_packet_approval": {
        "action_id": "review_packet_approval",
        "label": "Review packet approval",
        "category": "controlled",
        "risk_level": "low",
        "requires_approval": False,
        "writes_files": True,
        "runs_commands": False,
        "allowed_paths": ["09_exports/interface_phase_1/approval_ledger/"],
        "forbidden_capabilities": [],
        "menu_option": None,
        "cli_flags": ["--review-packet", "--approve-packet", "--reject-packet"],
        "description": "Review, approve, or reject prepared command packets. Approval is tracked in the ledger but never executed.",
        "recommended_next_action": "show_approval_ledger",
    },
    "show_approval_ledger": {
        "action_id": "show_approval_ledger",
        "label": "Show approval ledger",
        "category": "controlled",
        "risk_level": "none",
        "requires_approval": False,
        "writes_files": False,
        "runs_commands": False,
        "allowed_paths": ["09_exports/interface_phase_1/approval_ledger/"],
        "forbidden_capabilities": [],
        "menu_option": "10",
        "cli_flags": ["--show-approval-ledger"],
        "description": "Display the approval ledger showing lifecycle states of all prepared command packets.",
        "recommended_next_action": "review_packet_approval or prepare_command_packet",
    },
}
