#!/usr/bin/env python3
"""Phase 5 + Original +1 + Original +1B master validator wall."""

from pathlib import Path
import json
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parent.parent
DIST = ROOT / "13_web_dashboard" / "dist"
STATIC = ROOT / "13_web_dashboard" / "static"
PHASE5 = ROOT / "09_exports" / "interface_phase_5"
PLUS1 = ROOT / "09_exports" / "original_plus1"

errors = []


def check(condition, message):
    if not condition:
        errors.append(message)


def file_contains(path, text):
    return path.exists() and text in path.read_text(encoding="utf-8", errors="replace")


def js_safety_check(path):
    if not path.exists():
        errors.append(f"Missing JS file: {path.relative_to(ROOT)}")
        return
    text = path.read_text(encoding="utf-8", errors="replace")
    for token in [
        "localStorage", "sessionStorage", "document.cookie", "indexedDB", "IndexedDB", "caches.", "serviceWorker",
        "WebSocket", "EventSource", "sendBeacon", "eval(", "Function(", "import(", "Blob", "URL.createObjectURL", "FileReader",
    ]:
        check(token not in text, f"dashboard.js contains forbidden token: {token}")
    manual_feedback_import_allowed = "/api/feedback?action=import" in text and "mvp31-submit-feedback-packet" in text
    for method in ['method: "POST"', "method:'POST'", 'method: "PUT"', "method:'PUT'", 'method: "PATCH"', "method:'PATCH'", 'method: "DELETE"', "method:'DELETE'"]:
        if method in text and not manual_feedback_import_allowed:
            check(False, f"dashboard.js contains forbidden HTTP method: {method}")
    allowed_fetches = {
        "./original_plus2c_audit_log_model.json",
        "./original_plus2d_approval_gate_model.json",
        "./original_plus2e_dry_run_engine_model.json",
        "/api/audit-log-status",
        "/api/approval-gate-status",
        "/api/dry-run-status",
        "/api/health",
        "/api/status",
        "/api/backend-manifest",
        "/api/auth-status",
        "/api/role-matrix",
        "/api/request-storage-status",
        "/api/feedback",
        "/api/feedback?action=import",
        "./status_snapshot.json",
        "./phase4d_identity_schema.json",
        "./phase4d_action_schema.json",
        "./phase4d_audit_schema.json",
        "./phase4d_approval_schema.json",
        "./phase4d_risk_model.json",
        "./original_plus1b_contract_schemas.json",
        "./original_plus1c_readiness_qa_model.json",
        "./original_plus1d_backend_boundary_model.json",
        "./original_plus1e_backend_build_tickets.json",
        "./original_plus2a_auth_foundation_model.json",
        "./original_plus2b_request_storage_model.json",
        "./mvp7_real_authenticated_reads_model.json",
        "./mvp8_controlled_request_create_model.json",
        "./mvp9_request_detail_lifecycle_model.json",
        "./mvp10_operator_workspace_model.json",
        "./mvp11_token_aware_workspace_polish_model.json",
        "./mvp12_controlled_lifecycle_event_model.json",
        "./mvp13_request_activity_safe_errors_model.json",
        "./mvp14_manual_live_workspace_test_model.json",
        "./mvp15_live_test_demo_pitch_model.json",
        "./mvp16_live_test_results_demo_package_model.json",
        "./mvp17_external_demo_package_model.json",
        "./mvp18_share_ready_external_review_model.json",
        "./mvp19_external_feedback_model.json",
        "./mvp20_manual_feedback_review_model.json",
        "./mvp21_safe_feedback_persistence_model.json",
        "./mvp22_controlled_feedback_import_write_model.json",
        "./mvp23_feedback_import_smoke_test_model.json",
        "./mvp24_beta_feedback_import_workspace_model.json",
        "./mvp25_authenticated_feedback_review_inbox_model.json",
        "./mvp26_feedback_synthesis_product_decision_model.json",
        "./mvp27_feedback_to_request_conversion_model.json",
        "./mvp28_operator_roadmap_prioritization_model.json",
        "./mvp29_guided_product_demo_control_room_model.json",
        "./mvp30_pitchable_release_package_model.json",
        "/api/request-read-smoke-status",
        "/api/request-write-smoke-status",
        "/api/lifecycle-event-smoke-status",
    }
    for target in re.findall(r'fetch\(["\']([^"\']+)["\']', text):
        check(target in allowed_fetches, f"dashboard.js unauthorized fetch: {target}")


report_requirements = [
    (PHASE5 / "original_phase_5_final_acceptance_report.md", "PHASE_5_COMPLETE"),
    (PHASE5 / "original_phase_5_final_production_summary.md", "PRODUCTION_VISIBLE"),
    (PHASE5 / "original_phase_5e_production_verification_report.md", "PRODUCTION_VERIFIED"),
    (PLUS1 / "original_plus1_production_verification_report.md", "PRODUCTION_VERIFIED"),
    (PLUS1 / "original_plus1b_production_verification_report.md", "PRODUCTION_VERIFIED"),
    (PLUS1 / "original_plus1c_production_verification_report.md", "PRODUCTION_VERIFIED"),
    (PLUS1 / "original_plus1d_production_verification_report.md", "PRODUCTION_VERIFIED"),
    (PLUS1 / "original_plus1_acceptance_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1b_acceptance_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1c_acceptance_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1d_acceptance_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1b_operator_console_consolidation_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1b_automation_contract_layer_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1b_contract_schema_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1b_master_validator_wall_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1b_design_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1b_safety_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1c_acceptance_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1c_readiness_scoring_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1c_contract_qa_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1c_no_go_decision_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1c_dependency_gap_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1c_validator_confidence_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1c_design_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1c_safety_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1d_backend_boundary_blueprint_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1d_real_automation_dependency_map_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1d_endpoint_contract_map_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1d_auth_permission_architecture_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1d_storage_audit_approval_models_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1d_queue_job_lifecycle_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1d_mutation_gateway_boundary_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1d_future_integration_boundary_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1d_secrets_rollback_rate_limit_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1d_design_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1d_safety_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (PLUS1 / "original_plus1d_acceptance_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp5_acceptance_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp5_migration_readiness_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp5_manual_migration_review_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp5_authenticated_request_reads_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp5_request_read_adapter_contract_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp5_security_boundary_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp5_next_product_step_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp6_controlled_migration_apply_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp6_migration_apply_result_report.md", "PASS_WITH_NOTES"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp6_post_migration_verification_report.md", "PASS_WITH_NOTES"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp6_authenticated_reads_enablement_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp6_feature_flag_enablement_report.md", "PASS_WITH_NOTES"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp6_security_boundary_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp6_next_product_step_report.md", "PASS_WITH_HIGH_CONFIDENCE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp6_acceptance_report.md", "PASS_WITH_CONDITIONAL_LIVE_DEPENDENCY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp6_validator_wall_review.md", "PASS_WITH_TARGETED_VALIDATION"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp7_acceptance_report.md", "REAL_AUTHENTICATED_SUPABASE_READS_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp7_real_authenticated_reads_report.md", "REAL_AUTHENTICATED_READS_IMPLEMENTED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp7_auth_token_validation_report.md", "IMPLEMENTED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp7_postgrest_read_adapter_report.md", "IMPLEMENTED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp7_request_endpoint_actions_report.md", "IMPLEMENTED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp7_read_smoke_test_report.md", "PASS_WITH_TOKEN_TEST_OPTIONAL"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp7_security_boundary_report.md", "VERIFIED_FOR_READS"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp7_next_product_step_report.md", "READY_FOR_VERIFICATION"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp7_requests_endpoint_hardening_report.md", "PASS_WITH_TARGETED_HARDENING"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp8_acceptance_report.md", "CONTROLLED_AUTHENTICATED_REQUEST_CREATE_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp8_controlled_request_create_report.md", "CONTROLLED_REQUEST_CREATE_WRITE_IMPLEMENTED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp8_payload_schema_report.md", "DEFINED_AND_ENFORCED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp8_write_gate_report.md", "ACTIVE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp8_blocked_actions_report.md", "ENFORCED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp8_create_smoke_test_report.md", "PASS_WITH_CREATE_SMOKE_TEST_OPTIONAL"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp8_security_boundary_report.md", "VERIFIED_FOR_CREATION"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp8_next_product_step_report.md", "READY_FOR_VERIFICATION"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp8_write_path_review_report.md", "PASS_WITH_TARGETED_REVIEW"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp9_acceptance_report.md", "REQUEST_DETAIL_LIFECYCLE_TIMELINE_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp9_request_list_ui_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp9_request_detail_ui_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp9_lifecycle_timeline_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp9_create_verification_harness_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp9_security_boundary_report.md", "VERIFIED_FOR_UI_MODELS"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp9_next_product_step_report.md", "READY_FOR_WORKSPACE_UI"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp10_acceptance_report.md", "OPERATOR_REQUEST_WORKSPACE_UI_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp10_api_client_report.md", "IMPLEMENTED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp10_create_form_report.md", "IMPLEMENTED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp10_next_product_step_report.md", "READY_FOR_POLISH"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp10_operator_workspace_ui_report.md", "OPERATOR_REQUEST_WORKSPACE_UI_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp10_request_panels_report.md", "IMPLEMENTED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp10_security_boundary_report.md", "VERIFIED_FOR_WORKSPACE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp10_token_handling_report.md", "MEMORY_ONLY_ENFORCED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp10_actual_token_storage_review.md", "PASS_WITH_TARGETED_REVIEW"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp11_acceptance_report.md", "TOKEN_AWARE_WORKSPACE_REQUEST_WORKFLOW_POLISH_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp11_error_empty_states_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp11_next_product_step_report.md", "READY_FOR_LIFECYCLE_WRITES"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp11_request_list_controls_report.md", "IMPLEMENTED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp11_request_workflow_ux_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp11_security_boundary_report.md", "VERIFIED_FOR_WORKSPACE_POLISH"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp11_token_aware_session_report.md", "IMPLEMENTED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp11_workspace_state_machine_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp11_real_token_runtime_review.md", "PASS_WITH_TARGETED_REVIEW"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp12_acceptance_report.md", "CONTROLLED_LIFECYCLE_EVENT_CREATION_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp12_blocked_actions_report.md", "ENFORCED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp12_controlled_lifecycle_event_report.md", "CONTROLLED_LIFECYCLE_EVENT_CREATION_IMPLEMENTED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp12_event_payload_schema_report.md", "DEFINED_AND_ENFORCED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp12_event_write_gate_report.md", "ACTIVE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp12_lifecycle_event_smoke_test_report.md", "PASS_WITH_LIFECYCLE_EVENT_SMOKE_TEST_OPTIONAL"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp12_next_product_step_report.md", "READY_FOR_VERIFICATION"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp12_security_boundary_report.md", "VERIFIED_FOR_LIFECYCLE_CREATION"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp12_timeline_refresh_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp12_safe_error_hardening_report.md", "PASS_WITH_TARGETED_HARDENING"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp12_validator_wall_review.md", "PASS_WITH_TARGETED_VALIDATION"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp13_acceptance_report.md", "REQUEST_ACTIVITY_FEED_SAFE_ERRORS_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp13_safe_api_error_report.md", "IMPLEMENTED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp13_request_activity_feed_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp13_activity_filtering_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp13_timeline_empty_error_states_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp13_timeline_refresh_ux_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp13_security_boundary_report.md", "VERIFIED_FOR_ACTIVITY_FEED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp13_next_product_step_report.md", "READY_FOR_LIFECYCLE_TEST"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp13_safe_error_normalization_report.md", "PASS_WITH_TARGETED_HARDENING"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp13_validator_wall_review.md", "PASS_WITH_TARGETED_VALIDATION"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp14_acceptance_report.md", "MANUAL_LIVE_WORKSPACE_TEST_HARNESS_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp14_live_test_checklist_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp14_demo_readiness_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp14_manual_test_result_capture_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp14_safe_testing_boundary_report.md", "VERIFIED_FOR_LIVE_TESTING"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp14_next_product_step_report.md", "READY_FOR_FINAL_VERIFICATION"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp14_validator_wall_review.md", "PASS_WITH_TARGETED_VALIDATION"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp15_acceptance_report.md", "LIVE_TEST_EXECUTION_DEMO_PITCH_FLOW_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp15_live_test_execution_plan_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp15_live_test_execution_result_report.md", "LIVE_TEST_NOT_RUN_TOKEN_REQUIRED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp15_safe_result_template_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp15_demo_pitch_flow_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp15_product_readiness_scorecard_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp15_known_limitations_safety_boundary_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp15_next_product_step_report.md", "READY_FOR_DEMO_PITCH"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp15_validator_wall_review.md", "PASS_WITH_TARGETED_VALIDATION"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp16_acceptance_report.md", "LIVE_TEST_RESULTS_DEMO_PITCH_PACKAGE_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp16_live_test_results_report.md", "LIVE_TEST_NOT_RUN_TOKEN_REQUIRED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp16_demo_pitch_package_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp16_product_one_pager_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp16_demo_walkthrough_script_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp16_technical_architecture_summary_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp16_safety_boundary_report.md", "VERIFIED_FOR_DEMO_PACKAGE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp16_next_product_step_report.md", "READY_FOR_EXTERNAL_DEMO"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp16_validator_wall_review.md", "PASS_WITH_TARGETED_VALIDATION"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp17_acceptance_report.md", "EXTERNAL_DEMO_PACKAGE_PITCH_ASSETS_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp17_public_product_summary_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp17_reviewer_brief_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp17_safety_boundary_brief_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp17_demo_walkthrough_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp17_demo_q_and_a_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp17_known_limitations_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp17_next_product_step_report.md", "READY_FOR_EXTERNAL_REVIEW"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp17_validator_wall_review.md", "PASS_WITH_TARGETED_VALIDATION"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp18_acceptance_report.md", "SHARE_READY_EXTERNAL_REVIEW_PORTAL_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp18_share_ready_external_review_portal_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp18_review_packet_index_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp18_role_based_review_paths_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp18_demo_package_qa_report.md", "QA_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp18_share_safe_checklist_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp18_feedback_prompts_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp18_safety_boundary_report.md", "VERIFIED_FOR_SHARE_READY_PORTAL"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp18_next_product_step_report.md", "READY_FOR_EXTERNAL_FEEDBACK"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp18_validator_wall_review.md", "PASS_WITH_TARGETED_VALIDATION"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp19_acceptance_report.md", "EXTERNAL_FEEDBACK_INTAKE_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp19_feedback_intake_model_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp19_reviewer_response_capture_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp19_feedback_review_queue_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp19_feedback_synthesis_readiness_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp19_external_demo_feedback_package_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp19_security_boundary_report.md", "VERIFIED_FOR_STATIC_FEEDBACK"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp19_next_product_step_report.md", "READY_FOR_FEEDBACK_COLLECTION"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp19_validator_wall_review.md", "PASS_WITH_TARGETED_VALIDATION"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp19_production_verification_report.md", "PRODUCTION_VERIFIED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp20_acceptance_report.md", "MANUAL_FEEDBACK_IMPORT_REVIEW_QUEUE_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp20_manual_feedback_import_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp20_review_queue_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp20_synthesis_workspace_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp20_review_to_product_decision_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp20_security_boundary_report.md", "VERIFIED_FOR_STATIC_MEMORY_ONLY_FEEDBACK"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp20_next_product_step_report.md", "READY_FOR_EXTERNAL_FEEDBACK_ROUND_OR_SAFE_PERSISTENCE_REVIEW"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp20_validator_quality_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp20_validator_wall_review.md", "PASS_WITH_TARGETED_VALIDATION"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp21_acceptance_report.md", "SAFE_FEEDBACK_PERSISTENCE_READINESS_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp21_safe_feedback_persistence_readiness_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp21_feedback_schema_review_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp21_feedback_rls_policy_review_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp21_feedback_api_contract_review_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp21_feedback_feature_flag_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp21_security_boundary_report.md", "VERIFIED_FOR_PERSISTENCE_READINESS_ONLY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp21_next_product_step_report.md", "READY_FOR_CONTROLLED_FEEDBACK_IMPORT_WRITE_REVIEW"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp21_validator_quality_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp21_validator_wall_review.md", "PASS_WITH_TARGETED_VALIDATION"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp22_acceptance_report.md", "CONTROLLED_FEEDBACK_IMPORT_WRITE_IMPLEMENTED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp22_controlled_feedback_import_write_report.md", "IMPLEMENTED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp22_feedback_payload_validator_report.md", "IMPLEMENTED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp22_feedback_write_client_report.md", "IMPLEMENTED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp22_feedback_api_endpoint_report.md", "IMPLEMENTED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp22_feedback_migration_files_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp22_feedback_write_gate_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp22_feedback_smoke_status_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp22_security_boundary_report.md", "VERIFIED_FOR_CONTROLLED_FEEDBACK_IMPORT_WRITE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp22_next_product_step_report.md", "READY_FOR_MANUAL_MIGRATION_AND_TOKEN_GATED_SMOKE_TEST"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp22_validator_quality_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp22_validator_wall_review.md", "PASS_WITH_TARGETED_VALIDATION"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp23_acceptance_report.md", "TOKEN_GATED_FEEDBACK_IMPORT_SMOKE_TEST_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp23_manual_migration_operator_flow_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp23_token_gated_smoke_test_harness_report.md", "IMPLEMENTED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp23_feedback_migration_verification_report.md", "IMPLEMENTED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp23_smoke_result_artifact_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp23_operator_decision_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp23_security_boundary_report.md", "VERIFIED_FOR_TOKEN_GATED_SMOKE_TEST"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp23_next_product_step_report.md", "READY_FOR_REVIEWED_MIGRATION_AND_TOKEN_GATED_SMOKE_TEST"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp23_validator_quality_report.md", "DEFINED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp23_validator_wall_review.md", "PASS_WITH_TARGETED_VALIDATION"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp24_acceptance_report.md", "PASS_WITH_TOKEN_IN_MEMORY_AND_FLAG_GATED_IMPORT"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp24_beta_feedback_import_workspace_report.md", "REVIEWED_BETA_FEEDBACK_IMPORT_WORKSPACE_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp24_beta_import_form_report.md", "PAYLOAD_VALIDATION_PREVIEW_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp24_beta_import_session_report.md", "TOKEN_IN_MEMORY_ONLY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp24_next_product_step_report.md", "NEXT_STEP_ADD_AUTHENTICATED_FEEDBACK_REVIEW_INBOX"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp24_security_boundary_report.md", "FEEDBACK_PERSISTENCE_DISABLED_HANDLED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp24_validator_quality_report.md", "NETLIFY_FUNCTION_ONLY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp24_validator_wall_review.md", "NO_AUTOMATIC_MIGRATION_APPLY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp25_acceptance_report.md", "PASS_WITH_OWNER_SCOPED_READ_ONLY_FEEDBACK_REVIEW"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp25_feedback_detail_report.md", "FEEDBACK_DETAIL_READ_API_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp25_feedback_read_api_report.md", "FEEDBACK_LIST_READ_API_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp25_feedback_review_inbox_report.md", "AUTHENTICATED_FEEDBACK_REVIEW_INBOX_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp25_feedback_synthesis_queue_report.md", "READ_ONLY_REVIEW_WORKFLOW"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp25_next_product_step_report.md", "NEXT_STEP_BUILD_FEEDBACK_SYNTHESIS_AND_PRODUCT_DECISION_WORKFLOW"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp25_security_boundary_report.md", "OWNER_SCOPED_RLS_READS"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp25_validator_quality_report.md", "SERVICE_ROLE_NOT_USED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp25_validator_wall_review.md", "UPDATE_DELETE_EXECUTE_BLOCKED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp26_acceptance_report.md", "PASS_WITH_READ_ONLY_MANUAL_SYNTHESIS"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp26_feedback_synthesis_workspace_report.md", "FEEDBACK_SYNTHESIS_PRODUCT_DECISION_WORKFLOW_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp26_theme_clustering_report.md", "THEME_CLUSTERING_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp26_product_decision_cards_report.md", "PRODUCT_DECISION_CARDS_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp26_signal_strength_report.md", "SIGNAL_STRENGTH_SCORING_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp26_security_boundary_report.md", "OWNER_SCOPED_FEEDBACK_READS"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp26_next_product_step_report.md", "NEXT_STEP_BUILD_FEEDBACK_TO_REQUEST_CONVERSION_WORKSPACE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp26_validator_quality_report.md", "SERVICE_ROLE_NOT_USED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp26_validator_wall_review.md", "UPDATE_DELETE_EXECUTE_BLOCKED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp27_acceptance_report.md", "PASS_WITH_OPTIONAL_SERVER_GATED_REQUEST_CREATE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp27_feedback_to_request_workspace_report.md", "FEEDBACK_TO_REQUEST_CONVERSION_WORKSPACE_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp27_request_draft_report.md", "REQUEST_DRAFT_FROM_FEEDBACK_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp27_request_payload_preview_report.md", "DECISION_TO_REQUEST_PAYLOAD_PREVIEW_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp27_controlled_request_creation_report.md", "CONTROLLED_REQUEST_CREATE_OPTIONAL"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp27_security_boundary_report.md", "SERVICE_ROLE_NOT_USED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp27_next_product_step_report.md", "NEXT_STEP_BUILD_OPERATOR_ROADMAP_PRIORITIZATION_BOARD"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp27_validator_quality_report.md", "REQUEST_WRITES_SERVER_GATED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp27_validator_wall_review.md", "NO_DIRECT_BROWSER_SUPABASE_ALLOWANCE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp28_acceptance_report.md", "PASS_WITH_READ_ONLY_ROADMAP_WORKFLOW"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp28_operator_roadmap_report.md", "OPERATOR_ROADMAP_PRIORITIZATION_BOARD_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp28_priority_scoring_report.md", "PRIORITY_SCORING_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp28_roadmap_lanes_report.md", "PRODUCT_DECISION_LANES_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp28_feedback_request_link_report.md", "FEEDBACK_SIGNALS_TO_ROADMAP_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp28_security_boundary_report.md", "SERVICE_ROLE_NOT_USED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp28_next_product_step_report.md", "NEXT_STEP_BUILD_GUIDED_PRODUCT_DEMO_CONTROL_ROOM"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp28_validator_quality_report.md", "IMPACT_EFFORT_CONFIDENCE_MATRIX_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp28_validator_wall_review.md", "NO ROADMAP AUTO-WRITE ALLOWANCE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp29_acceptance_report.md", "PASS_WITH_SAFE_DEMO_MODE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp29_guided_demo_control_room_report.md", "GUIDED_PRODUCT_DEMO_CONTROL_ROOM_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp29_demo_persona_paths_report.md", "ROLE_BASED_DEMO_PATHS_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp29_demo_storyline_report.md", "OPERATOR_STORYLINE_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp29_demo_readiness_scorecard_report.md", "DEMO_READINESS_SCORECARD_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp29_security_boundary_report.md", "NO_FAKE_LIVE_TEST_CLAIMS"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp29_next_product_step_report.md", "NEXT_STEP_REVIEW_DEMO_CONTROL_ROOM_AND_PREPARE_PITCHABLE_RELEASE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp29_validator_quality_report.md", "PASS_WITH_SAFE_DEMO_MODE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp29_validator_wall_review.md", "No fake live claims added"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp30_acceptance_report.md", "PASS_WITH_SAFE_RELEASE_EXPORTS"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp30_pitchable_release_package_report.md", "PITCHABLE_RELEASE_PACKAGE_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp30_product_narrative_export_report.md", "PRODUCT_NARRATIVE_EXPORT_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp30_capability_map_report.md", "RELEASE_CAPABILITY_MAP_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp30_audience_variants_report.md", "AUDIENCE_VARIANTS_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp30_demo_walkthrough_export_report.md", "DEMO_WALKTHROUGH_EXPORT_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp30_release_manifest_report.md", "PASS_WITH_SAFE_RELEASE_EXPORTS"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp30_security_boundary_report.md", "NO FAKE LIVE TEST CLAIMS"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp30_next_product_step_report.md", "NEXT_STEP_BUILD_DEMO_SESSION_CAPTURE_AND_EXTERNAL_REVIEW_LOOP"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp30_validator_quality_report.md", "PASS_WITH_SAFE_RELEASE_EXPORTS"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp30_validator_wall_review.md", "No release-package automation allowance added"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp31_acceptance_report.md", "PASS_WITH_MANUAL_SESSION_CAPTURE_AND_OPTIONAL_GATED_IMPORT"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp31_demo_session_capture_report.md", "DEMO_SESSION_CAPTURE_WORKSPACE_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp31_external_review_loop_report.md", "EXTERNAL_REVIEW_FEEDBACK_LOOP_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp31_reviewer_persona_session_report.md", "REVIEWER_PERSONA_SESSION_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp31_feedback_packet_draft_report.md", "FEEDBACK_PACKET_DRAFT_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp31_optional_feedback_import_report.md", "OPTIONAL_FEEDBACK_IMPORT_GATED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp31_follow_up_decision_report.md", "FOLLOW_UP_DECISION_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp31_security_boundary_report.md", "NO_AUTOMATED_OUTREACH"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp31_next_product_step_report.md", "NEXT_STEP_BUILD_RELEASE_REVIEW_METRICS_AND_SIGNAL_DASHBOARD"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp31_validator_quality_report.md", "PASS_WITH_MANUAL_SESSION_CAPTURE_AND_OPTIONAL_GATED_IMPORT"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp31_validator_wall_review.md", "MVP-31 Wall Coverage Added"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp32_release_review_metrics_dashboard_report.md", "RELEASE_REVIEW_METRICS_SIGNAL_DASHBOARD_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp32_reviewer_signal_summary_report.md", "REVIEWER_SIGNAL_SUMMARY_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp32_demo_session_signal_report.md", "DEMO_SESSION_SIGNAL_SUMMARY_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp32_release_readiness_metric_report.md", "RELEASE_READINESS_METRICS_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp32_product_decision_signal_rollup_report.md", "PRODUCT_DECISION_SIGNAL_ROLLUP_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp32_signal_packet_export_report.md", "EXPORTABLE_SIGNAL_PACKET_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp32_security_boundary_report.md", "SECURITY_BOUNDARY_INTACT"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp32_next_product_step_report.md", "NEXT_STEP_BUILD_PRODUCT_LAUNCH_READINESS_FINAL_PITCH_PACKET"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp32_validator_quality_report.md", "PASS_WITH_MANUAL_EXISTING_SIGNAL_ROLLUPS"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp32_acceptance_report.md", "PASS_WITH_MANUAL_EXISTING_SIGNAL_ROLLUPS"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp32_validator_wall_review.md", "MVP-32 Wall Coverage Added"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp33_product_launch_readiness_console_report.md", "PRODUCT_LAUNCH_READINESS_CONSOLE_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp33_final_pitch_packet_report.md", "FINAL_PITCH_PACKET_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp33_release_candidate_scorecard_report.md", "RELEASE_CANDIDATE_SCORECARD_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp33_stakeholder_pitch_variants_report.md", "STAKEHOLDER_PITCH_VARIANTS_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp33_operator_launch_decision_panel_report.md", "OPERATOR_LAUNCH_DECISION_PANEL_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp33_safety_readiness_one_pager_report.md", "SAFETY_READINESS_ONE_PAGER_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp33_security_boundary_report.md", "SECURITY_BOUNDARY_INTACT"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp33_next_product_step_report.md", "NEXT_STEP_REVIEW_FINAL_PITCH_PACKET_AND_PREPARE_RELEASE_CANDIDATE"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp33_validator_quality_report.md", "PASS_WITH_SAFE_LAUNCH_REVIEW_ONLY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp33_acceptance_report.md", "PRODUCT_LAUNCH_READINESS_FINAL_PITCH_PACKET_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp33_validator_wall_review.md", "MVP-33 Wall Coverage Added"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp34_public_release_candidate_review_portal_report.md", "PUBLIC_RELEASE_CANDIDATE_REVIEW_PORTAL_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp34_investor_recruiter_review_room_report.md", "INVESTOR_RECRUITER_REVIEW_ROOM_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp34_external_reviewer_paths_report.md", "EXTERNAL_REVIEWER_PATHS_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp34_public_safe_pitch_packet_report.md", "PUBLIC_SAFE_PITCH_PACKET_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp34_release_candidate_artifact_index_report.md", "RELEASE_CANDIDATE_ARTIFACT_INDEX_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp34_review_instruction_packet_report.md", "EXTERNAL_REVIEW_INSTRUCTIONS_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp34_security_boundary_report.md", "SECURITY_BOUNDARY_INTACT"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp34_next_product_step_report.md", "NEXT_STEP_BUILD_EXTERNAL_REVIEW_FEEDBACK_SUMMARY_AND_OUTREACH_PREP"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp34_validator_quality_report.md", "PASS_WITH_PUBLIC_SAFE_REVIEW_ROOM"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp34_acceptance_report.md", "PUBLIC_RELEASE_CANDIDATE_REVIEW_PORTAL_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp34_validator_wall_review.md", "MVP-34 Wall Coverage Added"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp35_external_review_feedback_summary_report.md", "EXTERNAL_REVIEW_FEEDBACK_SUMMARY_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp35_reviewer_response_matrix_report.md", "REVIEWER_RESPONSE_MATRIX_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp35_outreach_prep_workspace_report.md", "OUTREACH_PREP_WORKSPACE_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp35_follow_up_response_packet_report.md", "FOLLOW_UP_RESPONSE_PACKET_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp35_external_reviewer_reply_guide_report.md", "EXTERNAL_REVIEWER_REPLY_GUIDE_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp35_operator_follow_up_decision_report.md", "OPERATOR_FOLLOW_UP_DECISION_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp35_security_boundary_report.md", "SECURITY_BOUNDARY_INTACT"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp35_next_product_step_report.md", "NEXT_STEP_BUILD_REVIEW_TO_ROADMAP_DECISION_SYNC"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp35_validator_quality_report.md", "PASS_WITH_COPY_ONLY_OUTREACH_PREP"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp35_acceptance_report.md", "EXTERNAL_REVIEW_FEEDBACK_SUMMARY_OUTREACH_PREP_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp35_validator_wall_review.md", "MVP-35 Wall Coverage Added"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp36_acceptance_report.md", "PASS_WITH_OPERATOR_REVIEW_ONLY_SYNC"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp37_acceptance_report.md", "PASS_WITH_OPERATOR_REVIEW_ONLY_HANDOFF"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp38_acceptance_report.md", "PASS_WITH_OPERATOR_REVIEW_ONLY_FINAL_ROOM"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp38_production_verification_report.md", "PRODUCTION_VERIFIED"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp39_acceptance_report.md", "EXTERNAL_DEMO_REVIEW_SHARE_PACKAGE_LOCK_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp39_external_demo_review_share_package_lock_report.md", "READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp39_share_safe_package_index_report.md", "READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp39_role_based_external_reviewer_packet_report.md", "READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp39_copy_only_share_instruction_report.md", "READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp39_reviewer_safe_demo_walkthrough_report.md", "READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp39_share_readiness_validation_packet_report.md", "READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp39_security_boundary_report.md", "PASS"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp39_next_product_step_report.md", "NEXT_STEP_BUILD_REVIEWER_RESPONSE_CAPTURE_READINESS_LOCK"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp39_validator_quality_report.md", "PASS"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp39_validator_wall_review.md", "PASS"),
]
for path, marker in report_requirements:
    check(path.exists(), f"missing report: {path.relative_to(ROOT)}")
    if path.exists():
        check(marker in path.read_text(encoding="utf-8", errors="replace"), f"report missing marker: {path.name}")

mvp41_model_requirements = [
    ROOT / "14_backend" / "product_runtime" / "ui_models" / "controlled_reviewer_response_intake_blueprint_model.json",
    ROOT / "14_backend" / "product_runtime" / "ui_models" / "intake_route_design_proposal_model.json",
    ROOT / "14_backend" / "product_runtime" / "ui_models" / "manual_reviewer_response_import_path_model.json",
    ROOT / "14_backend" / "product_runtime" / "ui_models" / "operator_approval_gate_blueprint_model.json",
    ROOT / "14_backend" / "product_runtime" / "ui_models" / "reviewer_response_validation_rules_model.json",
    ROOT / "14_backend" / "product_runtime" / "ui_models" / "response_normalization_mapping_blueprint_model.json",
    ROOT / "14_backend" / "product_runtime" / "ui_models" / "controlled_intake_implementation_checklist_model.json",
    ROOT / "13_web_dashboard" / "dist" / "mvp41_controlled_reviewer_response_intake_blueprint_model.json",
]
for path in mvp41_model_requirements:
    check(path.exists(), f"missing MVP-41 model: {path.relative_to(ROOT)}")

mvp41_release_requirements = [
    ROOT / "09_exports" / "release_package" / "mvp41_controlled_reviewer_response_intake_blueprint.md",
    ROOT / "09_exports" / "release_package" / "mvp41_intake_route_design_proposal.md",
    ROOT / "09_exports" / "release_package" / "mvp41_manual_reviewer_response_import_path.md",
    ROOT / "09_exports" / "release_package" / "mvp41_operator_approval_gate_blueprint.md",
    ROOT / "09_exports" / "release_package" / "mvp41_reviewer_response_validation_rules.md",
    ROOT / "09_exports" / "release_package" / "mvp41_response_normalization_mapping_blueprint.md",
    ROOT / "09_exports" / "release_package" / "mvp41_controlled_intake_implementation_checklist.md",
    ROOT / "09_exports" / "release_package" / "mvp41_controlled_reviewer_response_intake_manifest.json",
]
for path in mvp41_release_requirements:
    check(path.exists(), f"missing MVP-41 release artifact: {path.relative_to(ROOT)}")

mvp41_report_requirements = [
    (ROOT / "09_exports" / "mvp_product_track" / "mvp41_controlled_reviewer_response_intake_blueprint_report.md", "CONTROLLED_REVIEWER_RESPONSE_INTAKE_BLUEPRINT_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp41_intake_route_design_proposal_report.md", "INTAKE_ROUTE_DESIGN_PROPOSAL_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp41_manual_reviewer_response_import_path_report.md", "MANUAL_REVIEWER_RESPONSE_IMPORT_PATH_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp41_operator_approval_gate_blueprint_report.md", "OPERATOR_APPROVAL_GATE_BLUEPRINT_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp41_reviewer_response_validation_rules_report.md", "REVIEWER_RESPONSE_VALIDATION_RULES_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp41_response_normalization_mapping_blueprint_report.md", "RESPONSE_NORMALIZATION_MAPPING_BLUEPRINT_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp41_controlled_intake_implementation_checklist_report.md", "CONTROLLED_INTAKE_IMPLEMENTATION_CHECKLIST_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp41_security_boundary_report.md", "PASS"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp41_next_product_step_report.md", "NEXT_STEP_BUILD_OPERATOR_CONTROLLED_RESPONSE_IMPORT_DRY_RUN"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp41_validator_quality_report.md", "PASS"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp41_acceptance_report.md", "CONTROLLED_REVIEWER_RESPONSE_INTAKE_BLUEPRINT_READY"),
    (ROOT / "09_exports" / "mvp_product_track" / "mvp41_validator_wall_review.md", "PASS"),
    (ROOT / "09_exports" / "mvp_product_track" / "live_dashboard_usability_refactor_after_mvp41_report.md", "LIVE_DASHBOARD_USABILITY_REFACTOR_AFTER_MVP41_COMPLETE"),
]
for path, marker in mvp41_report_requirements:
    check(path.exists(), f"missing MVP-41 report: {path.relative_to(ROOT)}")
    if path.exists():
        check(marker in path.read_text(encoding="utf-8", errors="replace"), f"MVP-41 report missing marker: {path.name}")

index = (DIST / "index.html").read_text(encoding="utf-8", errors="replace")
for marker in [
    "Original Phase 5A",
    "Original Phase 5B",
    "Original Phase 5C",
    "Original Phase 5D",
    "Original Phase 5E",
    "Original +1",
    "Original +1B",
    "Original +1C",
    "Original +1D",
    "BACKEND BOUNDARY BLUEPRINT",
    "REAL AUTOMATION DEPENDENCY MAP",
    "BLUEPRINT ONLY",
    "FUTURE IMPLEMENTATION ONLY",
    "READINESS SCORING",
    "CONTRACT QA",
    "NO-GO DECISION LAYER",
    "NO LIVE AUTOMATION",
    "NO EXECUTION",
    "NO MUTATION",
    "NO BACKEND WRITES",
    "READY_FOR_BACKEND_ARCHITECTURE_REVIEW_ONLY",
    "NOT_READY_FOR_REAL_AUTOMATION",
    "MIGRATION READINESS CHECK",
    "MANUAL MIGRATION REVIEW REQUIRED",
    "AUTHENTICATED REQUEST READS",
    "READS REQUIRE BEARER TOKEN",
    "ANON KEY + USER TOKEN ONLY",
    "SERVICE ROLE NOT USED FOR READS",
    "WRITES STILL DISABLED",
    "RLS REVIEW REQUIRED",
    "NO AUTOMATIC MIGRATION APPLY",
    "NEXT_STEP_MANUALLY_APPLY_MIGRATIONS_AND_ENABLE_AUTH_READS",
    "MVP-6",
    "CONTROLLED MIGRATION APPLY",
    "SCHEMA AND RLS MIGRATION",
    "POST-MIGRATION VERIFICATION",
    "AUTHENTICATED READS ENABLEMENT",
    "REQUEST API READS ENABLED TARGET",
    "REQUEST API WRITES STILL DISABLED",
    "SERVICE ROLE NOT EXPOSED TO BROWSER",
    "WRITES REQUIRE SEPARATE REVIEW",
    "NEXT_STEP_VERIFY_AUTHENTICATED_READS_WITH_REAL_USER_TOKEN",
    "MVP-7",
    "REAL AUTHENTICATED SUPABASE READS",
    "SUPABASE AUTH TOKEN VALIDATION",
    "POSTGREST READS ENABLED",
    "ANON KEY + USER BEARER TOKEN",
    "RLS-ENFORCED REQUEST READS",
    "SERVICE ROLE NOT USED",
    "WRITES STILL DISABLED",
    "POST WRITES BLOCKED",
    "VERIFY WITH REAL USER TOKEN",
    "MVP-8",
    "CONTROLLED REQUEST CREATE WRITE",
    "CREATE ONLY",
    "AUTHENTICATED POST REQUIRED",
    "STRICT PAYLOAD VALIDATION",
    "ANON KEY + USER BEARER TOKEN",
    "RLS-ENFORCED INSERT",
    "SERVICE ROLE NOT USED",
    "UPDATE DELETE EXECUTE BLOCKED",
    "AUTOMATION STILL DISABLED",
    "VERIFY CREATE WITH REAL USER TOKEN",
    "MVP-9",
    "REQUEST LIST UI MODEL",
    "REQUEST DETAIL UI MODEL",
    "LIFECYCLE TIMELINE",
    "USER-OWNED REQUESTS ONLY",
    "RLS-ENFORCED READS",
    "CREATE VERIFICATION HARNESS",
    "UPDATE DELETE EXECUTE BLOCKED",
    "SERVICE ROLE NOT USED",
    "AUTOMATION STILL DISABLED",
    "NEXT_STEP_BUILD_OPERATOR_REQUEST_WORKSPACE_UI",
    "MVP-10",
    "OPERATOR REQUEST WORKSPACE",
    "TOKEN IN MEMORY ONLY",
    "AUTH STATUS PANEL",
    "API STATUS PANEL",
    "REQUEST LIST PANEL",
    "REQUEST DETAIL PANEL",
    "LIFECYCLE TIMELINE PANEL",
    "DRY RUN RESULTS PANEL",
    "CREATE REQUEST FORM",
    "READ AND CREATE ONLY",
    "UPDATE DELETE EXECUTE BLOCKED",
    "SERVICE ROLE NOT USED",
    "AUTOMATION STILL DISABLED",
    "NEXT_STEP_ADD_TOKEN_AWARE_FRONTEND_SESSION_AND_REQUEST_WORKFLOW_POLISH",
    "MVP-12",
    "CONTROLLED LIFECYCLE EVENT CREATION",
    "OPERATOR NOTE CREATION",
    "AUTHENTICATED EVENT POST REQUIRED",
    "STRICT EVENT PAYLOAD VALIDATION",
    "ANON KEY + USER BEARER TOKEN",
    "RLS-ENFORCED EVENT INSERT",
    "TIMELINE REFRESH AFTER EVENT",
    "REQUEST ROW UPDATE BLOCKED",
    "UPDATE DELETE APPROVE EXECUTE BLOCKED",
    "SERVICE ROLE NOT USED",
    "AUTOMATION STILL DISABLED",
    "NEXT_STEP_VERIFY_LIFECYCLE_EVENT_CREATION_WITH_REAL_USER_TOKEN",
    "NOT_READY_FOR_REAL_AUTOMATION",
    "MVP-13",
    "REQUEST ACTIVITY FEED",
    "SAFE API ERROR UX",
    "RAW ERROR EXPOSURE BLOCKED",
    "TIMELINE FILTERING",
    "GROUPED ACTIVITY FEED",
    "EMPTY AND ERROR STATES",
    "COPY SAFE ERROR CODE",
    "USER-OWNED ACTIVITY ONLY",
    "RLS-ENFORCED EVENT READS",
    "REQUEST ROW UPDATE BLOCKED",
    "UPDATE DELETE APPROVE EXECUTE BLOCKED",
    "SERVICE ROLE NOT USED",
    "AUTOMATION STILL DISABLED",
    "NEXT_STEP_MANUAL_LIFECYCLE_EVENT_TEST_THEN_ACTIVITY_FEED_REFINEMENT",
    "MVP-14",
    "MANUAL LIVE WORKSPACE TEST HARNESS",
    "DEMO READINESS CHECKLIST",
    "LIVE TEST CHECKLIST",
    "SAFE MANUAL TEST RESULT CAPTURE",
    "MEMORY-ONLY TOKEN TESTING",
    "STATUS ENDPOINT CHECKS",
    "READ FLOW VERIFICATION",
    "Write Readiness Panel",
    "SAFE ERROR BEHAVIOR CHECK",
    "ACTIVITY FEED DEMO FLOW",
    "BLOCKED ACTIONS DEMO",
    "TOKEN STORAGE BLOCKED",
    "SERVICE ROLE NOT USED",
    "UPDATE DELETE APPROVE EXECUTE BLOCKED",
    "AUTOMATION STILL DISABLED",
    "NEXT_STEP_RUN_MANUAL_LIVE_WORKSPACE_TEST_WITH_REAL_USER_TOKEN",
    "NOT_READY_FOR_REAL_AUTOMATION",
    "MVP-15",
    "LIVE TEST EXECUTION PLAN",
    "SAFE TEST RESULT TEMPLATE",
    "DEMO PITCH FLOW",
    "PRODUCT READINESS SCORECARD",
    "KNOWN LIMITATIONS AND SAFETY BOUNDARY",
    "MANUAL TOKEN TEST REQUIRED",
    "MEMORY-ONLY TOKEN TESTING",
    "PRODUCTION WORKSPACE TEST SEQUENCE",
    "SAFE RESULT CAPTURE ONLY",
    "NO SECRET CAPTURE",
    "NO ENV MUTATION",
    "NO MIGRATION APPLY",
    "BLOCKED ACTIONS REMAIN BLOCKED",
    "SERVICE ROLE NOT USED",
    "AUTOMATION STILL DISABLED",
    "NEXT_STEP_RUN_LIVE_TEST_AND_CAPTURE_RESULTS",
    "MVP-16",
    "LIVE TEST RESULTS PACKAGE",
    "DEMO PITCH PACKAGE",
    "PRODUCT ONE-PAGER",
    "TECHNICAL ARCHITECTURE SUMMARY",
    "DEMO WALKTHROUGH SCRIPT",
    "SAFE RESULT CAPTURE",
    "NO TOKEN CAPTURE",
    "NO SECRET CAPTURE",
    "NO RAW ERROR CAPTURE",
    "PRODUCT READINESS UPDATE",
    "SAFETY-FIRST DEMO NARRATIVE",
    "MANUAL LIVE TEST STATUS",
    "BLOCKED ACTIONS REMAIN BLOCKED",
    "SERVICE ROLE NOT USED",
    "AUTOMATION STILL DISABLED",
    "NEXT_STEP_RUN_LIVE_TEST_OR_PREPARE_EXTERNAL_DEMO",
    "NOT_READY_FOR_REAL_AUTOMATION",
    "MVP-17",
    "EXTERNAL DEMO PACKAGE",
    "PUBLIC PRODUCT SUMMARY",
    "REVIEWER BRIEF",
    "TECHNICAL REVIEWER BRIEF",
    "RECRUITER BRIEF",
    "FOUNDER OPERATOR BRIEF",
    "SAFETY BOUNDARY BRIEF",
    "DEMO WALKTHROUGH SCRIPT",
    "DEMO Q AND A",
    "REVIEWER CHECKLIST",
    "KNOWN LIMITATIONS",
    "DO NOT OVERCLAIM LIVE TEST STATUS",
    "APPROVAL EXECUTION AUTOMATION BLOCKED",
    "SERVICE ROLE NOT USED",
    "NO SECRET DISCLOSURE",
    "NEXT_STEP_PREPARE_EXTERNAL_REVIEW_OR_RUN_LIVE_TEST_FIRST",
    "MVP-18",
    "SHARE-READY EXTERNAL REVIEW PORTAL",
    "REVIEW PACKET INDEX",
    "START HERE GUIDE",
    "ROLE-BASED REVIEW PATHS",
    "DEMO PACKAGE QA",
    "SHARE-SAFE CHECKLIST",
    "FEEDBACK PROMPTS",
    "REVIEWER PERSONA ROUTING",
    "FIVE MINUTE REVIEW PATH",
    "FIFTEEN MINUTE REVIEW PATH",
    "THIRTY MINUTE REVIEW PATH",
    "LIVE TEST STATUS NOT OVERCLAIMED",
    "APPROVAL EXECUTION AUTOMATION BLOCKED",
    "NO SECRET DISCLOSURE",
    "SERVICE ROLE NOT USED",
    "NEXT_STEP_REVIEW_PACKAGE_AND_PREPARE_EXTERNAL_FEEDBACK_ROUND",
    "MVP-19",
    "EXTERNAL FEEDBACK INTAKE",
    "REVIEWER RESPONSE CAPTURE",
    "STATIC FEEDBACK PACKET ONLY",
    "REVIEWER PERSONA ROUTING",
    "FEEDBACK REVIEW QUEUE",
    "FEEDBACK SYNTHESIS READINESS",
    "NO BACKEND FEEDBACK SUBMISSION",
    "NO BROWSER PERSISTENCE",
    "SERVICE ROLE NOT USED",
    "AUTOMATION STILL DISABLED",
    "NEXT_STEP_RUN_EXTERNAL_REVIEW_ROUND_OR_ADD_MANUAL_FEEDBACK_IMPORT_QUEUE",
    "MVP-20",
    "MANUAL FEEDBACK IMPORT",
    "REVIEW QUEUE READY",
    "MANUAL SYNTHESIS WORKSPACE",
    "REVIEW TO PRODUCT DECISION",
    "STATIC MEMORY ONLY WORKFLOW",
    "NO BACKEND FEEDBACK SUBMISSION",
    "NO BROWSER PERSISTENCE",
    "SERVICE ROLE NOT USED",
    "AUTOMATION STILL DISABLED",
    "NEXT_STEP_RUN_EXTERNAL_FEEDBACK_ROUND_OR_ADD_SAFE_FEEDBACK_PERSISTENCE",
    "MVP-21",
    "SAFE FEEDBACK PERSISTENCE READINESS",
    "SCHEMA REVIEW READY",
    "RLS POLICY REVIEW READY",
    "API CONTRACT REVIEW READY",
    "FEATURE FLAG DEFINED DISABLED",
    "NO MIGRATION APPLY",
    "NO FEEDBACK WRITES ENABLED",
    "SERVICE ROLE NOT USED",
    "AUTOMATION STILL DISABLED",
    "NEXT_STEP_REVIEW_AND_OPTIONALLY_BUILD_CONTROLLED_FEEDBACK_IMPORT_WRITE",
    "MVP-22",
    "CONTROLLED FEEDBACK IMPORT WRITE",
    "FEEDBACK IMPORT ENDPOINT READY",
    "PAYLOAD VALIDATION ENFORCED",
    "OWNER-SCOPED INSERT DESIGNED",
    "FEATURE FLAG DISABLED BY DEFAULT",
    "FEEDBACK_PERSISTENCE_DISABLED",
    "SERVICE ROLE NOT USED",
    "NO MIGRATION APPLY",
    "UPDATE DELETE EXECUTE BLOCKED",
    "AUTOMATION STILL DISABLED",
    "NEXT_STEP_MANUALLY_APPLY_FEEDBACK_MIGRATION_AND_RUN_TOKEN_GATED_IMPORT_SMOKE_TEST",
    "MVP-23",
    "TOKEN-GATED FEEDBACK IMPORT SMOKE TEST",
    "MANUAL MIGRATION OPERATOR FLOW",
    "DISABLED MODE VERIFICATION",
    "LIVE IMPORT TEST OPTIONAL AND GATED",
    "TOKENS NOT STORED OR PRINTED",
    "SERVICE ROLE NOT USED",
    "NO AUTOMATIC MIGRATION APPLY",
    "UPDATE DELETE EXECUTE BLOCKED",
    "AUTOMATION STILL DISABLED",
    "NEXT_STEP_RUN_REVIEWED_MIGRATION_AND_TOKEN_GATED_SMOKE_TEST",
    "MVP-24",
    "REVIEWED BETA FEEDBACK IMPORT WORKSPACE",
    "TOKEN IN MEMORY ONLY",
    "FEEDBACK ENDPOINT STATUS PANEL",
    "MIGRATION READINESS PANEL",
    "FEEDBACK PACKET IMPORT FORM",
    "PAYLOAD VALIDATION PREVIEW",
    "FEEDBACK_PERSISTENCE_DISABLED HANDLED",
    "NETLIFY FUNCTION ONLY",
    "SERVICE ROLE NOT USED",
    "NO AUTOMATIC MIGRATION APPLY",
    "UPDATE DELETE EXECUTE BLOCKED",
    "AUTOMATION STILL DISABLED",
    "NEXT_STEP_ADD_AUTHENTICATED_FEEDBACK_REVIEW_INBOX",
    "MVP-25",
    "AUTHENTICATED FEEDBACK REVIEW INBOX",
    "FEEDBACK LIST READ API",
    "FEEDBACK DETAIL READ API",
    "OWNER-SCOPED RLS READS",
    "FEEDBACK SYNTHESIS QUEUE",
    "READ ONLY REVIEW WORKFLOW",
    "SERVICE ROLE NOT USED",
    "UPDATE DELETE EXECUTE BLOCKED",
    "AUTOMATION STILL DISABLED",
    "NEXT_STEP_BUILD_FEEDBACK_SYNTHESIS_AND_PRODUCT_DECISION_WORKFLOW",
    "NOT_READY_FOR_REAL_AUTOMATION",
    "MVP-26",
    "FEEDBACK SYNTHESIS WORKSPACE",
    "THEME CLUSTERING",
    "PRODUCT DECISION CARDS",
    "SIGNAL STRENGTH SCORING",
    "READ ONLY SYNTHESIS QUEUE",
    "OWNER-SCOPED FEEDBACK READS",
    "NEXT_STEP_BUILD_FEEDBACK_TO_REQUEST_CONVERSION_WORKSPACE",
    "PASS_WITH_READ_ONLY_MANUAL_SYNTHESIS",
    "MVP-27",
    "FEEDBACK TO REQUEST CONVERSION WORKSPACE",
    "REQUEST DRAFT FROM FEEDBACK",
    "DECISION TO REQUEST PAYLOAD PREVIEW",
    "CONTROLLED REQUEST CREATE OPTIONAL",
    "TOKEN IN MEMORY ONLY",
    "REQUEST WRITES SERVER GATED",
    "NEXT_STEP_BUILD_OPERATOR_ROADMAP_PRIORITIZATION_BOARD",
    "PASS_WITH_OPTIONAL_SERVER_GATED_REQUEST_CREATE",
    "MVP-28",
    "OPERATOR ROADMAP PRIORITIZATION BOARD",
    "FEEDBACK SIGNALS TO ROADMAP",
    "PRODUCT DECISION LANES",
    "PRIORITY SCORING",
    "IMPACT EFFORT CONFIDENCE MATRIX",
    "READ ONLY ROADMAP WORKFLOW",
    "NEXT_STEP_BUILD_GUIDED_PRODUCT_DEMO_CONTROL_ROOM",
    "PASS_WITH_READ_ONLY_ROADMAP_WORKFLOW",
    "MVP-29",
    "GUIDED PRODUCT DEMO CONTROL ROOM",
    "ROLE BASED DEMO PATHS",
    "OPERATOR STORYLINE",
    "DEMO READINESS SCORECARD",
    "NO FAKE LIVE TEST CLAIMS",
    "NEXT_STEP_REVIEW_DEMO_CONTROL_ROOM_AND_PREPARE_PITCHABLE_RELEASE",
    "PASS_WITH_SAFE_DEMO_MODE",
    "MVP-30",
    "PITCHABLE RELEASE PACKAGE",
    "PRODUCT NARRATIVE EXPORT",
    "RELEASE CAPABILITY MAP",
    "AUDIENCE VARIANTS",
    "DEMO WALKTHROUGH EXPORT",
    "SAFETY BOUNDARY SUMMARY",
    "SAFE DEMO MODE",
    "NEXT_STEP_BUILD_DEMO_SESSION_CAPTURE_AND_EXTERNAL_REVIEW_LOOP",
    "PASS_WITH_SAFE_RELEASE_EXPORTS",
    "MVP-31",
    "DEMO SESSION CAPTURE WORKSPACE",
    "EXTERNAL REVIEW FEEDBACK LOOP",
    "REVIEWER PERSONA SESSION",
    "DEMO SESSION NOTES",
    "FEEDBACK PACKET DRAFT",
    "OPTIONAL FEEDBACK IMPORT GATED",
    "TOKEN IN MEMORY ONLY",
    "NO AUTOMATED OUTREACH",
    "NO FAKE REVIEWER RESULTS",
    "NEXT_STEP_BUILD_RELEASE_REVIEW_METRICS_AND_SIGNAL_DASHBOARD",
    "PASS_WITH_MANUAL_SESSION_CAPTURE_AND_OPTIONAL_GATED_IMPORT",
    "MVP-32",
    "RELEASE REVIEW METRICS DASHBOARD",
    "REVIEWER SIGNAL SUMMARY",
    "DEMO SESSION SIGNALS",
    "RELEASE READINESS METRICS",
    "PRODUCT DECISION SIGNAL ROLLUP",
    "ROADMAP SIGNAL ROLLUP",
    "EXPORTABLE SIGNAL PACKET",
    "NO FAKE METRICS",
    "NO FAKE REVIEWER RESULTS",
    "NEXT_STEP_BUILD_PRODUCT_LAUNCH_READINESS_FINAL_PITCH_PACKET",
    "PASS_WITH_MANUAL_EXISTING_SIGNAL_ROLLUPS",
    "MVP-33",
    "PRODUCT LAUNCH READINESS CONSOLE",
    "RELEASE CANDIDATE SCORECARD",
    "STAKEHOLDER PITCH VARIANTS",
    "OPERATOR LAUNCH DECISION PANEL",
    "SAFE LAUNCH REVIEW ONLY",
    "NO FAKE LAUNCH STATUS",
    "NO DEPLOY CONTROLS",
    "PASS_WITH_SAFE_LAUNCH_REVIEW_ONLY",
    "NEXT_STEP_REVIEW_FINAL_PITCH_PACKET_AND_PREPARE_RELEASE_CANDIDATE",
    "MVP-34",
    "PUBLIC RELEASE CANDIDATE REVIEW PORTAL",
    "INVESTOR RECRUITER REVIEW ROOM",
    "EXTERNAL REVIEWER PATHS",
    "PUBLIC SAFE PITCH PACKET",
    "RELEASE CANDIDATE ARTIFACT INDEX",
    "PUBLIC SAFE DEMO SCRIPT",
    "REVIEW QUESTIONS PREP GUIDE",
    "EXTERNAL REVIEW INSTRUCTIONS",
    "NO PUBLIC WRITES",
    "NO TOKEN INPUT",
    "NO SECRETS EXPOSED",
    "NO DEPLOY CONTROLS",
    "NO LAUNCH AUTOMATION",
    "NOT_READY_FOR_REAL_AUTOMATION",
    "PASS_WITH_PUBLIC_SAFE_REVIEW_ROOM",
    "NEXT_STEP_BUILD_EXTERNAL_REVIEW_FEEDBACK_SUMMARY_AND_OUTREACH_PREP",
    "MVP-35",
    "EXTERNAL REVIEW FEEDBACK SUMMARY",
    "REVIEWER RESPONSE MATRIX",
    "FEEDBACK THEMES",
    "OUTREACH PREP WORKSPACE",
    "FOLLOW UP RESPONSE PACKET",
    "EXTERNAL REVIEWER REPLY GUIDE",
    "OPERATOR FOLLOW UP DECISION PANEL",
    "OUTREACH PREP COPY BANK",
    "COPY ONLY OUTREACH PREP",
    "NO AUTOMATED OUTREACH",
    "NO CONTACT AUTOMATION",
    "NEXT_STEP_BUILD_REVIEW_TO_ROADMAP_DECISION_SYNC",
    "PASS_WITH_COPY_ONLY_OUTREACH_PREP",
    "MVP-36",
    "REVIEW TO ROADMAP DECISION SYNC",
    "EXTERNAL SIGNAL PRIORITY MAP",
    "ROADMAP UPDATE RECOMMENDATIONS",
    "REVIEW SIGNAL REQUEST DRAFTS",
    "DECISION SYNC AUDIT PACKET",
    "OPERATOR ROADMAP SYNC REVIEW",
    "REVIEW TO ROADMAP COPY BANK",
    "OPERATOR REVIEW ONLY",
    "NO AUTOMATIC ROADMAP UPDATES",
    "NO AUTOMATIC REQUEST CREATION",
    "NO LIVE WRITES",
    "NEXT_STEP_BUILD_RELEASE_CANDIDATE_DECISION_LOG_AND_HANDOFF",
    "PASS_WITH_OPERATOR_REVIEW_ONLY_SYNC",
    "MVP-37",
    "RELEASE CANDIDATE DECISION LOG",
    "DECISION RATIONALE TRAIL",
    "ROADMAP SYNC HANDOFF PACKET",
    "REQUEST DRAFT HANDOFF",
    "STAKEHOLDER HANDOFF SUMMARY",
    "OPERATOR RELEASE HANDOFF REVIEW",
    "RELEASE CANDIDATE HANDOFF COPY BANK",
    "NO AUTOMATIC RELEASE APPROVAL",
    "PASS_WITH_OPERATOR_REVIEW_ONLY_HANDOFF",
    "NEXT_STEP_BUILD_FINAL_RELEASE_REVIEW_ROOM_AND_DEMO_SCRIPT_LOCK",
    "MVP-38",
    "FINAL RELEASE REVIEW ROOM",
    "DEMO SCRIPT LOCK",
    "REVIEWER WALKTHROUGH PATH",
    "FINAL REVIEW AUDIENCE PATHS",
    "RELEASE GO NO GO CHECKLIST",
    "DEMO TIMING TALKING POINTS",
    "FINAL RELEASE REVIEW COPY BANK",
    "FINAL REVIEW ONLY",
    "DEMO SCRIPT LOCKED",
    "NO DEPLOYMENT",
    "PASS_WITH_OPERATOR_REVIEW_ONLY_FINAL_ROOM",
    "NEXT_STEP_BUILD_EXTERNAL_DEMO_REVIEW_SHARE_PACKAGE_LOCK",
    "MVP-39",
    "EXTERNAL DEMO REVIEW SHARE PACKAGE LOCK",
    "SHARE SAFE PACKAGE INDEX",
    "ROLE BASED EXTERNAL REVIEWER PACKETS",
    "COPY ONLY SHARE INSTRUCTIONS",
    "REVIEWER SAFE DEMO WALKTHROUGH",
    "SHARE READINESS VALIDATION PACKET",
    "SHARE PACKAGE LOCKED",
    "COPY ONLY SHARING",
    "PACKAGE NOT SENT",
    "NO REVIEWER CONTACT",
    "NEXT_STEP_BUILD_REVIEWER_RESPONSE_CAPTURE_READINESS_LOCK",
    "PASS_WITH_COPY_ONLY_SHARE_PACKAGE_LOCK",
    "MVP-40",
    "REVIEWER RESPONSE CAPTURE READINESS LOCK",
    "REVIEWER RESPONSE SCHEMA PROPOSAL",
    "CAPTURE SAFETY REQUIREMENTS",
    "OPERATOR RESPONSE REVIEW QUEUE READINESS",
    "RESPONSE TO FEEDBACK MAPPING READINESS",
    "RESPONSE TRIAGE READINESS RULES",
    "FUTURE CAPTURE IMPLEMENTATION CHECKLIST",
    "OPERATOR REVIEW ONLY",
    "READINESS ONLY",
    "FUTURE IMPLEMENTATION ONLY",
    "NO PUBLIC ENDPOINT",
    "NO PUBLIC RESPONSE SUBMISSION",
    "NO REVIEWER RESPONSE WRITES",
    "NO RESPONSE CAPTURE ENABLED",
    "NO RESPONSE PERSISTENCE ENABLED",
    "NO AUTOMATIC IMPORT",
    "NO EMAIL SENDING",
    "NO REVIEWER CONTACT",
    "NO AUTOMATED OUTREACH",
    "NO LIVE WRITES",
    "NO PUBLIC WRITES",
    "NO TOKEN INPUT",
    "SERVICE ROLE NOT USED",
    "UPDATE DELETE EXECUTE BLOCKED",
    "NOT_READY_FOR_REAL_AUTOMATION",
    "NEXT_STEP_BUILD_CONTROLLED_REVIEWER_RESPONSE_INTAKE_BLUEPRINT",
    "MVP-41",
    "CONTROLLED REVIEWER RESPONSE INTAKE BLUEPRINT",
    "INTAKE ROUTE DESIGN PROPOSAL",
    "MANUAL REVIEWER RESPONSE IMPORT PATH",
    "OPERATOR APPROVAL GATE BLUEPRINT",
    "REVIEWER RESPONSE VALIDATION RULES",
    "RESPONSE NORMALIZATION MAPPING BLUEPRINT",
    "CONTROLLED INTAKE IMPLEMENTATION CHECKLIST",
    "OPERATOR REVIEW ONLY",
    "BLUEPRINT ONLY",
    "FUTURE IMPLEMENTATION ONLY",
    "NO PUBLIC ENDPOINT",
    "NO LIVE INTAKE",
    "NO PUBLIC RESPONSE SUBMISSION",
    "NO REVIEWER RESPONSE WRITES",
    "NO RESPONSE CAPTURE ENABLED",
    "NO RESPONSE PERSISTENCE ENABLED",
    "NO AUTOMATIC IMPORT",
    "NO EMAIL SENDING",
    "NO REVIEWER CONTACT",
    "NO AUTOMATED OUTREACH",
    "NO LIVE WRITES",
    "NO PUBLIC WRITES",
    "NO TOKEN INPUT",
    "SERVICE ROLE NOT USED",
    "UPDATE DELETE EXECUTE BLOCKED",
    "NOT_READY_FOR_REAL_AUTOMATION",
    "NEXT_STEP_BUILD_OPERATOR_CONTROLLED_RESPONSE_IMPORT_DRY_RUN",
]:
    check(marker in index, f"index.html missing required marker: {marker}")

for match in re.finditer(r'(<button[^>]*>)([^<]+)(</button>)', index):
    tag, button_label, _ = match.groups()
    if "disabled" in tag.lower():
        continue
    clean = button_label.strip().lower()
    if clean.startswith("copy ") or clean.startswith("load ") or clean.startswith("phase ") or clean.startswith("original +"):
        continue
    if clean == "submit feedback packet manually":
        continue
    if any(word in clean for word in ["deploy", "merge", "push", "execute", "submit", "save", "queue", "create pr"]):
        check(False, f"index.html has forbidden enabled button label: {button_label.strip()}")

js_safety_check(STATIC / "dashboard.js")
js_safety_check(DIST / "static" / "dashboard.js")

changed = subprocess.run(
    ["git", "diff", "--name-only", "origin/master..HEAD"],
    capture_output=True,
    text=True,
    cwd=ROOT,
).stdout.strip().splitlines()

allowed_prefixes = [
        "scripts/validate_original_plus2c",
        "scripts/validate_original_plus2b",
        "scripts/validate_original_plus2a",
        "scripts/validate_mvp2_local_durable_request_persistence.py",
        "scripts/validate_mvp2_local_durable_request_persistence_e2e.py",
        "scripts/validate_mvp3_supabase_provider_request_api.py",
        "scripts/validate_mvp3_supabase_provider_request_api_e2e.py",
        "scripts/validate_mvp4_supabase_auth_rls_request_api.py",
        "scripts/validate_mvp4_supabase_auth_rls_request_api_e2e.py",
        "scripts/validate_mvp5_migration_readiness_authenticated_reads.py",
        "scripts/validate_mvp5_migration_readiness_authenticated_reads_e2e.py",
        "scripts/validate_mvp6_controlled_migration_authenticated_reads.py",
        "scripts/validate_mvp6_controlled_migration_authenticated_reads_e2e.py",
        "scripts/validate_mvp7_real_authenticated_supabase_reads.py",
        "scripts/validate_mvp7_real_authenticated_supabase_reads_e2e.py",
        "scripts/validate_mvp8_controlled_authenticated_request_create.py",
        "scripts/validate_mvp8_controlled_authenticated_request_create_e2e.py",
        "scripts/validate_mvp9_request_detail_lifecycle_timeline.py",
        "scripts/validate_mvp9_request_detail_lifecycle_timeline_e2e.py",
        "scripts/validate_mvp10_operator_request_workspace_ui.py",
        "scripts/validate_mvp10_operator_request_workspace_ui_e2e.py",
        "scripts/validate_mvp11_token_aware_workspace_polish.py",
        "scripts/validate_mvp11_token_aware_workspace_polish_e2e.py",
        "scripts/validate_mvp12_controlled_lifecycle_event_creation.py",
        "scripts/validate_mvp12_controlled_lifecycle_event_creation_e2e.py",
        "scripts/validate_mvp13_request_activity_feed_safe_errors.py",
        "scripts/validate_mvp13_request_activity_feed_safe_errors_e2e.py",
        "scripts/validate_mvp14_manual_live_workspace_test_harness.py",
        "scripts/validate_mvp14_manual_live_workspace_test_harness_e2e.py",
        "scripts/validate_mvp15_live_test_execution_demo_pitch.py",
        "scripts/validate_mvp15_live_test_execution_demo_pitch_e2e.py",
        "scripts/validate_mvp16_live_test_results_demo_package.py",
        "scripts/validate_mvp16_live_test_results_demo_package_e2e.py",
        "scripts/validate_mvp17_external_demo_package.py",
        "scripts/validate_mvp17_external_demo_package_e2e.py",
        "scripts/validate_mvp18_share_ready_external_review_portal.py",
        "scripts/validate_mvp18_share_ready_external_review_portal_e2e.py",
        "scripts/validate_mvp19_external_feedback_intake.py",
        "scripts/validate_mvp19_external_feedback_intake_e2e.py",
        "scripts/validate_mvp20_manual_feedback_import_review_queue.py",
        "scripts/validate_mvp20_manual_feedback_import_review_queue_e2e.py",
        "scripts/validate_mvp21_safe_feedback_persistence_readiness.py",
        "scripts/validate_mvp21_safe_feedback_persistence_readiness_e2e.py",
        "scripts/validate_mvp22_controlled_feedback_import_write.py",
        "scripts/validate_mvp22_controlled_feedback_import_write_e2e.py",
        "scripts/validate_mvp23_feedback_import_smoke_test.py",
        "scripts/validate_mvp23_feedback_import_smoke_test_e2e.py",
        "scripts/validate_mvp24_beta_feedback_import_workspace.py",
        "scripts/validate_mvp24_beta_feedback_import_workspace_e2e.py",
        "scripts/validate_mvp25_authenticated_feedback_review_inbox.py",
        "scripts/validate_mvp25_authenticated_feedback_review_inbox_e2e.py",
        "scripts/validate_mvp26_feedback_synthesis_product_decision.py",
        "scripts/validate_mvp26_feedback_synthesis_product_decision_e2e.py",
        "scripts/validate_mvp27_feedback_to_request_conversion.py",
        "scripts/validate_mvp27_feedback_to_request_conversion_e2e.py",
        "scripts/validate_mvp28_operator_roadmap_prioritization.py",
        "scripts/validate_mvp28_operator_roadmap_prioritization_e2e.py",
        "scripts/validate_mvp29_guided_product_demo_control_room.py",
        "scripts/validate_mvp29_guided_product_demo_control_room_e2e.py",
        "scripts/validate_mvp30_pitchable_release_package.py",
        "scripts/validate_mvp30_pitchable_release_package_e2e.py",
        "scripts/validate_mvp31_demo_session_capture_review_loop.py",
        "scripts/validate_mvp31_demo_session_capture_review_loop_e2e.py",
        "scripts/validate_mvp32_release_review_metrics_signal_dashboard.py",
        "scripts/validate_mvp32_release_review_metrics_signal_dashboard_e2e.py",
        "scripts/validate_mvp33_product_launch_readiness_final_pitch_packet.py",
        "scripts/validate_mvp33_product_launch_readiness_final_pitch_packet_e2e.py",
        "scripts/validate_mvp34_public_release_candidate_review_portal.py",
        "scripts/validate_mvp34_public_release_candidate_review_portal_e2e.py",
        "scripts/validate_mvp35_external_review_feedback_summary_outreach_prep.py",
        "scripts/validate_mvp35_external_review_feedback_summary_outreach_prep_e2e.py",
        "scripts/validate_mvp36_review_to_roadmap_decision_sync.py",
        "scripts/validate_mvp36_review_to_roadmap_decision_sync_e2e.py",
        "scripts/validate_mvp37_release_candidate_decision_log_handoff.py",
        "scripts/validate_mvp37_release_candidate_decision_log_handoff_e2e.py",
        "scripts/validate_mvp38_final_release_review_room_demo_script_lock.py",
        "scripts/validate_mvp38_final_release_review_room_demo_script_lock_e2e.py",
        "scripts/validate_mvp39_external_demo_review_share_package_lock.py",
        "scripts/validate_mvp39_external_demo_review_share_package_lock_e2e.py",
        "scripts/validate_mvp40_reviewer_response_capture_readiness_lock.py",
        "scripts/validate_mvp40_reviewer_response_capture_readiness_lock_e2e.py",
        "scripts/validate_mvp41_controlled_reviewer_response_intake_blueprint.py",
        "scripts/validate_mvp41_controlled_reviewer_response_intake_blueprint_e2e.py",
        "scripts/validate_live_dashboard_usability_after_mvp41.py",
        "scripts/validation_helpers_control_scan.py",
        "scripts/test_validation_helpers_control_scan.py",        "scripts/validate_live_page_context_aware_control_scan.py",
        "scripts/_validator_runner.py",
        "scripts/mvp23_feedback_import_smoke_test.py",
        "scripts/mvp23_verify_feedback_migration_files.py",
        "13_web_dashboard/",
        "09_exports/interface_phase_5/",
        "09_exports/original_plus1/",
        "09_exports/original_plus2/",
        "09_exports/mvp_product_track/",
        "09_exports/release_package/",
        "09_exports/external_demo_package/",
        ".env.example",
        ".supabase.env.local.example",
        "AGENTS.md",
        ".gitignore",
        "14_backend/auth/",
        "14_backend/request_storage/",
        "14_backend/audit_log/",
        "14_backend/approval_gate/",
    "14_backend/dry_run/",
    "14_backend/product_runtime/",
    "netlify/functions/auth-status.js",
    "netlify/functions/role-matrix.js",
        "netlify/functions/request-storage-status.js",
        "netlify/functions/audit-log-status.js",
        "netlify/functions/approval-gate-status.js",
        "netlify/functions/dry-run-status.js",
        "netlify/functions/product-runtime-status.js",
    "netlify/functions/provider-status.js",
    "netlify/functions/auth-status.js",
    "netlify/functions/requests.js",
    "netlify/functions/feedback.js",
    "netlify/functions/feedback-write-smoke-status.js",
    "netlify/functions/request-readiness-status.js",
    "netlify/functions/backend-manifest.js",
    "netlify/functions/request-read-smoke-status.js",
    "netlify/functions/request-write-smoke-status.js",
    "netlify/functions/_shared/provider_config.js",
    "netlify/functions/_shared/supabase_read_client.js",
    "netlify/functions/_shared/supabase_write_client.js",
    "netlify/functions/_shared/supabase_feedback_read_client.js",
    "netlify/functions/_shared/supabase_feedback_write_client.js",
    "netlify/functions/_shared/supabase_lifecycle_write_client.js",
    "netlify/functions/_shared/request_payload_validator.js",
    "netlify/functions/_shared/feedback_payload_validator.js",
    "netlify/functions/_shared/lifecycle_event_payload_validator.js",
    "netlify/functions/_shared/auth_context.js",
    "netlify/functions/_shared/safe_error.js",
    "netlify/functions/lifecycle-event-smoke-status.js",
    "netlify/functions/_shared/models/",
    "scripts/validate_original_plus1b_operator_console_contract_layer.py",
    "scripts/validate_original_plus1b_operator_console_contract_layer_e2e.py",
    "scripts/validate_original_plus1c_readiness_scoring_contract_qa.py",
    "scripts/validate_original_plus1c_readiness_scoring_contract_qa_e2e.py",
    "scripts/validate_original_plus1d_backend_boundary_blueprint.py",
    "scripts/validate_original_plus1d_backend_boundary_blueprint_e2e.py",
    "scripts/validate_original_plus1e_backend_implementation_gate.py",
    "scripts/validate_original_plus1e_backend_implementation_gate_e2e.py",
    "scripts/validate_original_plus2a_backend_auth_foundation.py",
    "scripts/validate_original_plus2a_backend_auth_foundation_e2e.py",
    "scripts/validate_original_plus2b_persistent_request_storage.py",
    "scripts/validate_original_plus2b_persistent_request_storage_e2e.py",
    "scripts/validate_original_plus2c_immutable_audit_log.py",
    "scripts/validate_original_plus2c_immutable_audit_log_e2e.py",
    "scripts/validate_original_plus2d_approval_gate_storage.py",
    "scripts/validate_original_plus2d_approval_gate_storage_e2e.py",
    "scripts/validate_original_plus2e_server_side_dry_run_engine.py",
    "scripts/validate_original_plus2e_server_side_dry_run_engine_e2e.py",
    "scripts/validate_mvp1_request_lifecycle_runtime.py",
    "scripts/validate_mvp1_request_lifecycle_runtime_e2e.py",
    "scripts/validate_phase5_plus1_master_validator_wall.py",
    "scripts/validate_backend_phase_4a_e2e.py",
    "scripts/validate_backend_phase_4b_planning.py",
    "scripts/validate_backend_phase_4c_planning.py",
    "scripts/validate_backend_phase_4d_strategic_e2e.py",
    "scripts/validate_interface_phase_3_e2e.py",
    "scripts/validate_original_phase_4_hosted_dashboard_e2e.py",
    "scripts/validate_original_phase_5a_client_side_workflow_e2e.py",
    "scripts/validate_original_phase_5a_client_side_workflow_shell.py",
    "scripts/validate_original_phase_5b_request_packet_builder.py",
    "scripts/validate_original_plus1_controlled_automation_readiness.py",
    "scripts/validate_original_plus1_controlled_automation_readiness_e2e.py",
    "scripts/validate_original_phase_5b_request_packet_builder_e2e.py",
    "scripts/validate_original_phase_5c_review_board.py",
    "scripts/validate_backend_phase_4d_disabled_ui.py",
    "scripts/validate_interface_phase_3_dashboard.py",
    "scripts/validate_original_phase_5c_review_board_e2e.py",
    "scripts/validate_original_phase_5d_handoff_composer.py",
    "scripts/validate_original_phase_5d_handoff_composer_e2e.py",
    "scripts/validate_original_phase_5e_runbook_simulator.py",
    "scripts/validate_original_phase_5e_runbook_simulator_e2e.py",
]

forbidden_prefixes = [
    "09_exports/interface_phase_1/",
    "09_exports/interface_phase_2/",
    "09_exports/interface_phase_3/",
    "09_exports/interface_phase_4/",
    "11_interface/",
    "12_tui/",
    "10_runtime/",
]

for path in changed:
    for prefix in forbidden_prefixes:
        check(not path.startswith(prefix), f"Forbidden changed path: {path}")
    check(any(path.startswith(prefix) for prefix in allowed_prefixes), f"Unexpected changed path: {path}")

if errors:
    print("VALIDATION_FAIL")
    for error in errors:
        print(f"  - {error}")
    sys.exit(1)

print("PHASE5_PLUS1_MASTER_VALIDATOR_WALL_PASS")
